apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-nest
  annotations:
    github.com/project-slug: pitrud/test-nest
    backstage.io/techdocs-ref: value
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://test-nest-plum.vercel.app/api-json
